spring:
  cloud:
    function:
      definition: consumer
    stream:
      default:
        producer:
          useNativeEncoding: true
      bindings:
        consumer-in-0:
          destination: input-topic
          group: some-group
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 1000
            backOffMaxInterval: 5000
            backOffMultiplier: 2

      kafka:
        binder:
          consumer-properties:
            "value.deserializer": org.springframework.kafka.support.serializer.JsonDeserializer
            "auto.offset.reset": "earliest"
            "group.instance.id": "1"
            "spring.json.trusted.packages": "com.vinsguru.cloudstreamkafkaplayground.sec11.dto"
